# Starter pipeline
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ws-svc-nsgtest-dev-nonprod-nsgtest'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage account show'